### ISSUE TITLE
Status of this crate

### ISSUE THREAD

**Issue by frewsxcv** [sfackler/hyper-native-tls#14]
From the README:

> native-tls support for Hyper. hyper-tls is currently made for async hyper, which isn't released yet.

Is the plan to eventually support Hyper 0.11? If not, should we tell people to use hyper-tls (which is released now)?

**Comment by sfackler** [comment]
Given that hyper-tls already exists I don't see any reason to update this as well. I'll update things to note that hyper-native-tls should only be used for hyper 0.10.
