### ISSUE TITLE
Not compatible with the latest version of hyper (0.11.2)

### ISSUE THREAD

**Issue by Ameobea** [sfackler/hyper-native-tls#15]
As of Hyper version 0.11.2, `use hyper::net::HttpsConnector` no longer exists.  I don't see `HttpsConnector` anywhere in the hyper documentation anywhere, as a matter of fact, and am not sure of the new way to support this.

If nothing else, the docs will need to be updated to support the new version of hyper, possibly requiring code changes to support it as well.

**Comment by sfackler** [comment]
Use hyper-tls for Hyper 0.11: https://github.com/sfackler/hyper-native-tls#warning
