### ISSUE TITLE
let NativeTlsClient::new() map to own error type

### ISSUE THREAD

**Issue by stsydow** [sfackler/hyper-native-tls#2]
The expression:
```
let ssl = try!(NativeTlsClient::new());
```
leads to:
```
the trait `std::convert::From<native_tls::Error>` is not implemented for 'my_crate:error:Error'
```
Should it not return Result< NativeTlsClient,hyper_native_tls::ServerError> or Result<NativeTlsClient,hyper_native_tls::ClientError> instead of the native_tls::Error?

Else one need to import native_tls crate too, to handle it properly.

**Comment by sfackler** [comment]
I think a solution here could be to publicly reexport `native_tls` from this crate, so you could access its contents via `hyper_native_tls::native_tls`. Seem reasonable?

**Comment by stsydow** [comment]
Yes would be ok for my use. Not the cleanest solution, but would work.
(Or should I use something else as web/https client?)
