### ISSUE TITLE
Would it be feasible to support PEM certificates?

### ISSUE THREAD

**Issue by shepmaster** [sfackler/hyper-native-tls#3]
From what I've seen, Let's Encrypt only offers PEM certificates. These can be converted <sup>1</sup> to PKCS12 certificates, but it's one annoying little step that we might be able to skip.

If you think it's feasible, I'd be happy to take a first crack at it, so any guidance would be appreciated.

---

**1** `openssl pkcs12 -export -out mysite.pkcs12 -in mysite.cer -inkey mysite.key -passout pass:hunter2`

**Comment by sfackler** [comment]
See sfackler/rust-native-tls#27 - I would prefer a more traditional setup as well, but it's a question of figuring out how to make that happen for macOS and Windows.

**Comment by shepmaster** [comment]
I see now that this crate is a wrapper around rust-native-tls, and all the interesting discussion will happen there. I'm cool with closing this.

You might want to update the README to point people like me towards rust-native-tls for issues that aren't specific to the the Hyper parts.  😇
