### ISSUE TITLE
relation between https://github.com/hyperium/hyper-tls

### ISSUE THREAD

**Issue by king6cong** [sfackler/hyper-native-tls#5]
Hi,

There seems to be multiple similar efforts towards getting TLS support for hyper.
This cause some dependency redundancy.

For example https://github.com/getsentry/sentry-rust relies on hyper-native-tls, where others rely on hyper-tls.

Maybe we should choose one and make it official and concentrate it afterwards?

**Comment by seanmonstar** [comment]
Well, hyper-tls is currently made for async hyper, which isn't released yet.
