### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by little-dude** [sfackler/hyper-native-tls#9]
Hi @sfackler !

Do you think you could make a new release? I'd like to use the ability to use custom certificates in `reqwest`. I have [a PR for this](https://github.com/seanmonstar/reqwest/pull/97), but it uses the github repo as a dependency for now.

**Comment by subscr1pt** [comment]
+1! I have a git dependency on this as well.

**Comment by sfackler** [comment]
I was looking things over in preparation for a release, and I don't think the method added in #97 is actually necessary. You can construct a `NativeTlsClient` from a `TlsConnector` via the `From` implementation. I'll update the documentation to call that out more explicitly.

**Comment by little-dude** [comment]
Which method are you talking about exactly?

**Comment by sfackler** [comment]
The builder and https://github.com/sfackler/hyper-native-tls/blob/master/src/lib.rs#L116

**Comment by little-dude** [comment]
I see. I submitted a PR that removes the `NativeTlsClientBuilder` introduced in #7

**Comment by martell** [comment]
Two new releases have been tagged since this was all merged.
Can we close this thread? Thanking you. :)
